behaviors:
  Hero3Agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 4096
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.85
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
    keep_checkpoints: 8
    max_steps: 20000000
    time_horizon: 128
    summary_freq: 1000
    threaded: true
environment_parameters:
  lesson_number:
    curriculum:
      - name: Lesson0 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Hero3Agent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0
        value: 2
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: Hero3Agent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2
        value: 3
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: Hero3Agent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 6
        value: 4
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: Hero3Agent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 8
        value: 5
      - name: Lesson4
        completion_criteria:
          measure: reward
          behavior: Hero3Agent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 10
        value: 6
      - name: Lesson5
        completion_criteria:
          measure: reward
          behavior: Hero3Agent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 12
        value: 7
      - name: Lesson6
        completion_criteria:
          measure: reward
          behavior: Hero3Agent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 15
        value: 8
      - name: Lesson7
        completion_criteria:
          measure: reward
          behavior: Hero3Agent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 20
        value: 9